### ISSUE TITLE
Wrong exception thrown when WebPReader#read index out of bounds

### ISSUE THREAD

**Issue by SamStephens** [usefulness/webp-imageio#136]
In WebPReader, when an invalid index is passed to #read, [an IllegalArgumentException is thrown](https://github.com/usefulness/webp-imageio/blob/6b08385484f26ac6de8f7ed8fdc6a26e41969908/webp-imageio/src/main/kotlin/com/luciad/imageio/webp/internal/WebPReader.kt#L90) using [Kotlin's require](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html).

However [the documentation of the implemented method, ImageReader#read](https://docs.oracle.com/javase/8/docs/api/javax/imageio/ImageReader.html#read-int-javax.imageio.ImageReadParam-), says that if the supplied index is out of bounds, an [IndexOutOfBoundsException](https://docs.oracle.com/javase/8/docs/api/java/lang/IndexOutOfBoundsException.html) should be thrown.

**Comment by mateuszkwiecinski** [comment]
Thanks for detailed report! Should be addressed in `0.5.1`
