### ISSUE TITLE
Document Proguard rules

### ISSUE THREAD

**Issue by mikedawson** [usefulness/webp-imageio#173]
Hi,

This library has been very useful to us to make it easy to support webp on our Desktop/JVM application. The only issue I found was when I enabled Proguard to shrink the app. 

These Proguard rules are required to keep the names used by the Service Provider:
```
-keep class javax.imageio.spi.ImageReaderSpi { *; }
-keep class com.luciad.imageio.webp.WebPImageWriterSpi { *; }
-keep class javax.imageio.spi.ImageReaderSpi { *; }
-keep class com.luciad.imageio.webp.WebPImageReaderSpi { *; }
```

Could that be added to README/documentation?

Thanks!

**Comment by mateuszkwiecinski** [comment]
Thanks for letting me know! 
I managed to [reproduce](https://github.com/usefulness/webp-imageio/tree/master/testing/proguard) this on my end, and came up with the following rules: https://github.com/usefulness/webp-imageio/blob/8408fbbd9bf3cad6b829e5d61b2236f2dc77fc58/webp-imageio/src/main/resources/META-INF/proguard/web-imageio.pro. They should be bundled and loaded automatically, so no documentation should be needed. 

I'm not sure I've got why you needed to keep `javax.imageio.spi.ImageReaderSpi`, here's R8 output when you attempt to keep the class:
<img width="741" alt="image" src="https://github.com/usefulness/webp-imageio/assets/36954793/ec756dbb-1be5-4bc4-b285-d04aa34081c5">

If you want, you can give the [snapshot version](https://github.com/usefulness/webp-imageio/packages/1476285) a try. I'll wait a bit for a confirmation everything works on your end and publish a regular release :)

**Comment by mikedawson** [comment]
Thank you for the quick reply!

On ```javax.imageio.spi.ImageReaderSpi``` - actually that was response to some strange warnings from my Desktop/compose proguard build that it considered javax.imagio a program class instead of a library class. It definitely shouldn't be needed in the proguard for webp-imageio.

I haven't seen rules being loaded automatically on JVM as happens on Android. I think most of the JVM world is still on Proguard (Jetpack Compose/Desktop is one of them), and don't load the rules automatically. I think it would be good to document it.

**Comment by mateuszkwiecinski** [comment]
Oh, interesting. I thought it became a standard already (since it is supported out-of-the-box by R8), but now I've found out for Proguard this is a standard, but only for Android builds: https://github.com/Guardsquare/proguard/issues/337 😮
